const data = [
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
  
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
    {
      itemName: "",
      image: "",
      price: "",
      category: "",
      isAvailable: "",
      availableQuantity: "",
    },
  ];
  